# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontEndShow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1254, 745)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.rgb_Qlabel = QtWidgets.QLabel(Form)
        self.rgb_Qlabel.setObjectName("rgb_Qlabel")
        self.gridLayout.addWidget(self.rgb_Qlabel, 0, 0, 1, 1)
        self.lidar_Qlabel = QtWidgets.QLabel(Form)
        self.lidar_Qlabel.setObjectName("lidar_Qlabel")
        self.gridLayout.addWidget(self.lidar_Qlabel, 0, 1, 1, 1)
        self.dvs_Qlabel = QtWidgets.QLabel(Form)
        self.dvs_Qlabel.setObjectName("dvs_Qlabel")
        self.gridLayout.addWidget(self.dvs_Qlabel, 0, 2, 1, 1)
        self.optical_flow_Qlabel = QtWidgets.QLabel(Form)
        self.optical_flow_Qlabel.setObjectName("optical_flow_Qlabel")
        self.gridLayout.addWidget(self.optical_flow_Qlabel, 1, 0, 1, 1)
        self.rgb_Distorted_Qlabel = QtWidgets.QLabel(Form)
        self.rgb_Distorted_Qlabel.setObjectName("rgb_Distorted_Qlabel")
        self.gridLayout.addWidget(self.rgb_Distorted_Qlabel, 1, 1, 1, 1)
        self.semantic_Qlabel = QtWidgets.QLabel(Form)
        self.semantic_Qlabel.setObjectName("semantic_Qlabel")
        self.gridLayout.addWidget(self.semantic_Qlabel, 1, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.rgb_Qlabel.setText(_translate("Form", "show camera RGB, cc.Raw"))
        self.lidar_Qlabel.setText(_translate("Form", "show Lidar"))
        self.dvs_Qlabel.setText(_translate("Form", "show camera dvs, cc.Raw"))
        self.optical_flow_Qlabel.setText(_translate("Form", "show camera optical_flow"))
        self.rgb_Distorted_Qlabel.setText(_translate("Form", "show camera RGB Distorted, cc.Raw"))
        self.semantic_Qlabel.setText(_translate("Form", "show camera semantic_segmentation, cc.Raw"))
